-- Vanilla - 1.1.5
local Data = {}

Data.GetTileData = function()
    -- Any tile not listed will have a random tree placed on it assuming the player can walk on the tile, otherwise no tree.
    return {
        ["grass-1"] = {"allow-trees", {{0, 0.7}, {1, 1}}},
        ["grass-2"] = {"allow-trees", {{0.45, 0.45}, {1, 0.8}}},
        ["grass-3"] = {"allow-trees", {{0, 0.6}, {0.65, 0.9}}},
        ["grass-4"] = {"allow-trees", {{0, 0.5}, {0.55, 0.7}}},
        ["dry-dirt"] = {"allow-trees", {{0.45, 0}, {0.55, 0.35}}},
        ["dirt-1"] = {"allow-trees", {{0, 0.25}, {0.45, 0.3}}, {{0.4, 0}, {0.45, 0.25}}},
        ["dirt-2"] = {"allow-trees", {{0, 0.3}, {0.45, 0.35}}},
        ["dirt-3"] = {"allow-trees", {{0, 0.35}, {0.55, 0.4}}},
        ["dirt-4"] = {"allow-trees", {{0.55, 0}, {0.6, 0.35}}, {{0.6, 0.3}, {1, 0.35}}},
        ["dirt-5"] = {"allow-trees", {{0, 0.4}, {0.55, 0.45}}},
        ["dirt-6"] = {"allow-trees", {{0, 0.45}, {0.55, 0.5}}},
        ["dirt-7"] = {"allow-trees", {{0, 0.5}, {0.55, 0.55}}},
        ["sand-1"] = {"allow-trees", {{0, 0}, {0.25, 0.15}}},
        ["sand-2"] = {"allow-trees", {{0, 0.15}, {0.3, 0.2}}, {{0.25, 0}, {0.3, 0.15}}},
        ["sand-3"] = {"allow-trees", {{0, 0.2}, {0.4, 0.25}}, {{0.3, 0}, {0.4, 0.2}}},
        ["red-desert-0"] = {"allow-trees", {{0.55, 0.35}, {1, 0.5}}},
        ["red-desert-1"] = {"allow-trees", {{0.6, 0}, {0.7, 0.3}}, {{0.7, 0.25}, {1, 0.3}}},
        ["red-desert-2"] = {"allow-trees", {{0.7, 0}, {0.8, 0.25}}, {{0.8, 0.2}, {1, 0.25}}},
        ["red-desert-3"] = {"allow-trees", {{0.8, 0}, {1, 0.2}}},
        ["water"] = {"water"},
        ["deepwater"] = {"water"},
        ["water-green"] = {"water"},
        ["deepwater-green"] = {"water"},
        ["water-shallow"] = {"water"},
        ["water-mud"] = {"water"},
        ["out-of-map"] = {"no-trees"},
        ["landfill"] = {"allow-trees", {{0, 0}, {0.25, 0.15}}}, --same as sand-1
        ["nuclear-ground"] = {"allow-trees", {{0, 0}, {0.25, 0.15}}} --same as sand-1
    }
end

--[[
    Generated by manually adding some code to the mod and running in 1.1.54 as the data was accessible via API at the time. This can't be obtained easily by reading the prototype files as their written values are manipulated in to the autoplace_specification values the API returned.

    All code goes in to biome_trees.lua BiomeTrees._GetTreeData():
        1: At start of function the below is added:
            -- Logging Tree Data
	        local logTreeDataString = ""
        2: Within the FOR loop just after the "treeData" is inserted in to the "treeDataArray":
            -- Logging Tree Data
			logTreeDataString = logTreeDataString .. "[\"" .. treeData.name .. "\"] = {\r\n" .. "name = \"" .. treeData.name .. "\",\r\n" .. "tempRange = {" .. treeData.tempRange[1] .. ", " .. treeData.tempRange[2] .. "},\r\n" .. "moistureRange = {" .. treeData.moistureRange[1] .. ", " .. treeData.moistureRange[2] .. "},\r\n" .. "probability = " .. treeData.probability .. "\r\n".. "},\r\n"
        3: At the end of the function before the return:
        	-- Logging Tree Data
        	log(logTreeDataString)
]]
Data.GetTreeData = function()
    return {
        ["tree-01"] = {
            name = "tree-01",
            tempRange = {25, 35},
            moistureRange = {0.5, 1},
            probability = 0.45
        },
        ["tree-02"] = {
            name = "tree-02",
            tempRange = {10, 24},
            moistureRange = {0.55, 0.75},
            probability = 0.45
        },
        ["tree-03"] = {
            name = "tree-03",
            tempRange = {18, 32},
            moistureRange = {0.6, 1},
            probability = 0.45
        },
        ["tree-04"] = {
            name = "tree-04",
            tempRange = {5, 19},
            moistureRange = {0.4, 0.8},
            probability = 0.45
        },
        ["tree-05"] = {
            name = "tree-05",
            tempRange = {5, 19},
            moistureRange = {0.6, 1},
            probability = 0.45
        },
        ["tree-09"] = {
            name = "tree-09",
            tempRange = {25, 35},
            moistureRange = {0.4, 0.5},
            probability = 0.25
        },
        ["tree-02-red"] = {
            name = "tree-02-red",
            tempRange = {10, 24},
            moistureRange = {0.4, 0.5},
            probability = 0.45
        },
        ["tree-07"] = {
            name = "tree-07",
            tempRange = {15, 35},
            moistureRange = {0.15, 0.25},
            probability = 0.2
        },
        ["tree-06"] = {
            name = "tree-06",
            tempRange = {9, 35},
            moistureRange = {0.05, 0.15},
            probability = 0.2
        },
        ["tree-06-brown"] = {
            name = "tree-06-brown",
            tempRange = {9, 35},
            moistureRange = {0.05, 0.15},
            probability = 0.2
        },
        ["tree-09-brown"] = {
            name = "tree-09-brown",
            tempRange = {15, 35},
            moistureRange = {0.15, 0.25},
            probability = 0.175
        },
        ["tree-09-red"] = {
            name = "tree-09-red",
            tempRange = {5, 25},
            moistureRange = {0.15, 0.25},
            probability = 0.17
        },
        ["tree-08"] = {
            name = "tree-08",
            tempRange = {15, 25},
            moistureRange = {0, 0.2},
            probability = 0.35
        },
        ["tree-08-brown"] = {
            name = "tree-08-brown",
            tempRange = {15, 25},
            moistureRange = {0, 0.2},
            probability = 0.35
        },
        ["tree-08-red"] = {
            name = "tree-08-red",
            tempRange = {-10, 0},
            moistureRange = {0, 0.1},
            probability = 0.45
        },
        ["dead-dry-hairy-tree"] = {
            name = "dead-dry-hairy-tree",
            tempRange = {-5, 35},
            moistureRange = {0, 0.3},
            probability = 0.005
        },
        ["dead-grey-trunk"] = {
            name = "dead-grey-trunk",
            tempRange = {-5, 35},
            moistureRange = {0, 0.3},
            probability = 0.01
        },
        ["dead-tree-desert"] = {
            name = "dead-tree-desert",
            tempRange = {-5, 35},
            moistureRange = {0, 0.3},
            probability = 0.005
        },
        ["dry-hairy-tree"] = {
            name = "dry-hairy-tree",
            tempRange = {-5, 35},
            moistureRange = {0, 0.3},
            probability = 0.005
        },
        ["dry-tree"] = {
            name = "dry-tree",
            tempRange = {-5, 35},
            moistureRange = {0, 0.3},
            probability = 0.005
        }
    }
end

return Data
